let readline = require("readline-sync")
console.log("module loaded...")
var data = readline.question("Enter the data")
var id = readline.questionInt("Enter the id")
var name = readline.question("Enter the name")
var salary = readline.questionFloat("Enter the salary")
var emaild = readline.questionEMail("Enter the emailid ")
console.log(data)
console.log("id is "+id)
console.log("name is "+name)
console.log("salary is "+salary)
console.log("emailid "+emaild)